/* eslint-disable @typescript-eslint/no-explicit-any */
import ResetPasswordForm from "@/components/pageComponets/reset-passwordForm";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Sovefi | Reset-password",
  description: "Generated by create SOVEFI",
};
const ResetPasswordPage = ({ params }: any) => {
  const token = params.token;

  return <ResetPasswordForm token={token} />;
};

export default ResetPasswordPage;
