import { AppSidebar } from "@/components/share/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sovefi | Profile",
  description: "Generated by create SOVEFI",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="mt-24">
      <SidebarProvider>
        <AppSidebar />
        <section>
          <SidebarTrigger />
          {children}
        </section>
      </SidebarProvider>
    </main>
  );
};

export default DashboardLayout;
