import { createSlice, configureStore } from "@reduxjs/toolkit";

// Define a slice for loan application steps
const applyLoanStepsSlice = createSlice({
  name: "applyLoanSteps",
  initialState: {
    step: 1,
  },
  reducers: {
    nextStep: (state) => {
      state.step += 1;
    },
    previousStep: (state) => {
      state.step -= 1;
    },
  },
});

// Export actions generated by createSlice
export const { nextStep, previousStep } = applyLoanStepsSlice.actions;

// Configure the Redux store with the slice reducer
const store = configureStore({
  reducer: applyLoanStepsSlice.reducer,
});

// Subscribe to store changes (for debugging)
store.subscribe(() => console.log(store.getState()));

// Dispatch actions to test the slice functionality
store.dispatch(nextStep()); // {step: 2}
store.dispatch(nextStep()); // {step: 3}
store.dispatch(previousStep()); // {step: 2}

export default applyLoanStepsSlice.reducer;
